[package]
name = "sozu-pulsar-connector"
version = "0.1.1"
edition = "2021"
authors = ["Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>"]

[dependencies]
anyhow = "^1.0.66"
clap = { version = "4.1.4", features = ["derive"] }
futures = "0.3"
envconfig = "0.10.0"
path-absolutize = "^3.0.14"
pulsar = "^6.0.0"
serde = { version = "^1.0.148", features = ["derive"] }
serde_json = "^1.0.89"
sozu-command-lib = "^0.14.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "^0.1.37"
tracing-subscriber = "^0.3.16"
