[batch]
temp_dir = "."
max_requests = 2000
max_size = 200000
interval = 15

[sozu]
config_path = "/absolute/path/to/your/sozu/config/config.toml"

[pulsar]
url = "pulsar+ssl://some-pulsar-url.com:2002"
token = "your_authentication_token_to_pulsar"
topic = "tenant/namespace/sozu-messages"
