---
name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        rust:
          - stable
          - beta
        include:
          - rust: nightly
            experimental: true
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}
...
